server {
    listen 80;
    server_name 202.155.91.204;

    root /var/www/simpanan;
    index index.html index.php;

    # Frontend
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend API
    location /api {
        alias /var/www/api-simpanan/public;
        try_files $uri $uri/ @api;

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
            # Kita arahkan langsung ke index.php di folder public Laravel
            fastcgi_param SCRIPT_FILENAME /var/www/api-simpanan/public/index.php;
            include fastcgi_params;
        }
    }

    location @api {
        # Kita kirimkan request asli termasuk /api/ ke Laravel
        rewrite ^/api/(.*)$ /api/index.php?/$1 last;
    }
}
