server {
    listen 80;
    server_name 202.155.91.204;

    root /var/www/siperjalan;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        alias /var/www/api-siperjalan/public;
        index index.php;
        try_files $uri $uri/ @api;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
            fastcgi_param SCRIPT_FILENAME /var/www/api-siperjalan/public/index.php;
            fastcgi_param REQUEST_URI $request_uri;
        }
    }

    location @api {
        rewrite ^/api/(.*)$ /api/index.php?/$1 last;
    }
}
