server {
    listen 80;
    server_name 202.155.91.204;

    # Global index
    index index.html index.php;

    # FRONTEND
    location / {
        root /var/www/siperjalan;
        try_files $uri $uri/ /index.html;
    }

    # BACKEND API
    location /api {
        root /var/www/api-siperjalan/public;
        rewrite ^/api/(.*)$ /$1 break;
        try_files $uri $uri/ /index.php?$query_string;

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
            fastcgi_param SCRIPT_FILENAME /var/www/api-siperjalan/public/index.php;
            include fastcgi_params;
        }
    }

    # STORAGE (Optional but good)
    location /storage {
        alias /var/www/api-siperjalan/storage/app/public;
        try_files $uri $uri/ =404;
    }
}
