server {
    listen 80;
    server_name 202.155.91.204;

    root /var/www/simpanan;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        alias /var/www/api-simpanan/public;
        index index.php;
        try_files $uri $uri/ /api/index.php?$query_string;

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
            fastcgi_param SCRIPT_FILENAME /var/www/api-simpanan/public/index.php;
        }
    }

    location /storage {
        alias /var/www/api-simpanan/storage/app/public;
    }
}
